apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet_nxt
  namespace: lahu2405
  labels:
    app: dotnet_nxt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet_nxt
  template:
    metadata:
      labels:
        app: dotnet_nxt
    spec:
      containers:
        - name: dotnet_nxt
          image: lahu2405arc.azurecr.io/lahu2405:#{Release.Artifacts.lahu2405.BuildId}#
         
          imagePullPolicy: Always

          ports:
            - containerPort: 5000
            - containerPort: 5001
      imagePullSecrets:
        - name: prdctmntc
--- 

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet_nxt
spec:
  type: LoadBalancer
  ports:
    - name: http5
      port: 5000
    - name: http51
      port: 5001
  selector:
    app: dotnet_nxt